export const START_LOADING_USERS = "START_LOADING_USERS";
export const LOADING_USERS_SUCCESS = "LOADING_USERS_SUCCESS";
export const LOADING_USERS_FAIL = "LOADING_USERS_FAIL";
export const END_LOADING_USERS = "END_LOADING_USERS";
